theme: jekyll-theme-minimal
title: Mingyu Cui
logo: /cmy.png
description: "I'm actively looking for Fall 2021 Co-op opportunities.\n------------------------------------------------------\nI am a Computer Engineering and Computer Science student at University of Southern California. I am undergrad teaching assistant for several courses at USC and participates regularly in research and ICPC contests."
