theme: jekyll-theme-minimal
title: Mingyu Cui
logo: /cmy.png
description: "Hi! I am a Software Engineer at Robinhood. I studied Computer Science at University of Southern California. I have been undergrad teaching assistant for several courses at USC and participates regularly in research projects, ICPC contests, and LeetCode contests."
