theme: jekyll-theme-minimal
title: Mingyu Cui
logo: /cmy.png
description: "I'm actively looking for full-time Software Engineer positions starting in 2022! I am a Computer Science student at University of Southern California. I am undergrad teaching assistant for several courses at USC and participates regularly in research and ICPC contests."
