theme: jekyll-theme-minimal
title: Mingyu Cui
logo: /cmy.png
description: "I am a Web Engineer at Robinhood. I studied Computer Science at University of Southern California. I am undergrad teaching assistant for several courses at USC and participates regularly in research and ICPC contests."
